version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/amd64 #only for MAC chip M
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/dbname
      - SECRET_KEY="your-secret-key"
    networks:
      - app-network

  db:
    image: mysql:8.0
    platform: linux/amd64 #only for MAC chip M
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_pid:/var/run/mysqld
    networks:
      - app-network
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-initialize-insecure

volumes:
  mysql_data:
  mysql_pid:

networks:
  app-network:
    driver: bridge
